// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkflnaokvqvuoaydhxux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZmxuYW9rdnF2dW9heWRoeHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTg5MjIsImV4cCI6MjA2ODEzNDkyMn0.E36pv3W3jvEe-wPxnjiCV4b071tZ0g1MKyoEiX5-MOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});